CREATE FUNCTION GETMAXSALARY
(
	@DEPNUM INT
)
RETURNS DECIMAL(18, 0)
AS
BEGIN
	DECLARE @RESULT DECIMAL(18, 0)
	SELECT @RESULT = MAX(empSalary)
	FROM dbo.tblEmployee
	WHERE depNum = @DEPNUM
	RETURN @RESULT
END


SELECT depNum, depName
	GETMAXSALARY (depNum) AS MAXSALARY
FROM dbo.tblDepartment
   